name: Build Docs and Deploy
on:
    push:
        paths: ['src/components/**']
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: ğŸ›ï¸ checkout
              uses: actions/checkout@v3

            - name: ğŸ“¦ install
              run: yarn install

            - name: ğŸ”§ build docs
              run: yarn build:docs

            - name: ğŸš€ deploy
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                  BRANCH: main
                  FOLDER: docs
                  CLEAN: true
                  TARGET_FOLDER: docs
